### ISSUE TITLE
AutoSetup.bat copies x64 files into Win32 folder

### ISSUE THREAD

**Issue by gweronimo** [arves100/llvm-vs2017-integration#3]
The following 4 lines (34-37) need to be corrected, changing Win32 into x64 :

copy Toolset-llvm-vs2017-x64.props "%VS_PROOT_DIR%\Win32\PlatformToolsets\LLVM-vs2017\Toolset.props"
copy Toolset-llvm-vs2017-x64.targets "%VS_PROOT_DIR%\Win32\PlatformToolsets\LLVM-vs2017\Toolset.targets"
copy Toolset-llvm-vs2017-xp-x64.props "%VS_PROOT_DIR%\Win32\PlatformToolsets\LLVM-vs2017_xp\Toolset.props"
copy Toolset-llvm-vs2017-xp-x64.targets "%VS_PROOT_DIR%\Win32\PlatformToolsets\LLVM-vs2017_xp\Toolset.targets"

**Comment by arves100** [comment]
Hi! Thank you for reporting, I've pushed a commit to fix this issue.
