### ISSUE TITLE
LLVM[clang] version

### ISSUE THREAD

**Issue by MVoz** [arves100/llvm-vs2017-integration#4]
собственно, в описании не указанно что версия должна быть 5.0 либо пути к либам и хидерам пусть исправлют

> Actually, the description does not specify that the version should be 5.0 and the paths to the libs and hiders are not true

`...\clang\5.0`
clang\5.0.0

**Comment by arves100** [comment]
This files were tested for clang 5.0. I forget that clang is version dipendent. I will investigate for alternatives. Regarding the path, I was able to use clang. What file is experiencing the issue?

**Comment by RoyiAvital** [comment]
Actually it is not clear what you add in that line.
It works without it.

I think you should add the path to:

1. Additional Header Folder - `$(LLVMInstallDir)\lib\clang\6.0.0\include` .
2. Library Path Folder - `$(LLVMInstallDir)\lib`.

Also, the version 6.0.0, could it be replaced with the version of Clang automatically?

**Comment by arves100** [comment]
Thanks for your information. I've pushed LLVM 6.0 compatibility under branch v6.0.
