### ISSUE TITLE
clang-cl not used in llvm >= 7.0.0

### ISSUE THREAD

**Issue by ghazel** [arves100/llvm-vs2017-integration#7]
Changing the version number as in https://github.com/arves100/llvm-vs2017-integration/issues/5 works for 6.0.0, but it does not work for future versions like 7.0.0 (or the 8.0.0 nightlies). When building,  MSVC uses `cl.exe` instead of `clang-cl.exe`.

What defined `clang-cl` as the compiler in these scripts?

**Comment by ghazel** [comment]
I see, previous versions had an `msbuild-bin` directory, with `cl.exe` (which appears to be an identical copy of `clang-cl.exe`).

This llvm integration will need to specify `cl`:

```xml
<PropertyGroup>
  <CLToolExe>clang-cl.exe</CLToolExe>
  <CLToolPath>$(LLVMInstallDir)\bin</CLToolPath>
</PropertyGroup>
```

**Comment by arves100** [comment]
I'm working on making a sort of python script that does everything by default, that's why I haven't answered, btw thanks for the information, I will surely add it (I will close this when the new commit gets pushed)

**Comment by arves100** [comment]
Thank you for your information, I've pushed a commit under branch v7.0 that adds support for LLVM 7.0.
